.TH TAPCONVERT "1" "July 2001" "" ""
.SH NAME
tapconvert \- convert Twisted configurations from one format to another
.SH SYNOPSIS
.B tapconvert -i \fIinput\fR -o \fIoutput\fR  [-f \fIinput-type\fR] [-t \fIoutput-type\fR] [-d] [-e]
.PP
.B tapconvert --help
.SH DESCRIPTION
.PP
The \fB\--help\fR prints out a usage message to standard output.
.TP 
\fB\--in\fR, \fB\-i\fR \fI<input file>\fR
The name of the input configuration.
.TP 
\fB\--out\fR, \fB\-o\fR \fI<output file>\fR
The name of the output configuration.
.TP 
\fB\--typein\fR, \fB\-f\fR \fI<input type>\fR
The type of the input file. Can be either 'guess', 'python', 'pickle', 'xml', or  'source'. Default is 'guess'.
.TP 
\fB\--typeout\fR, \fB\-t\fR \fI<output type>\fR
The type of the output file. Can be either 'pickle', 'xml', or  'source'. Default is 'source'.
.TP 
\fB\--decrypt\fR, \fB\-d\fR
Decrypt the specified tap/aos/xml input file.
.TP 
\fB\--encrypt\fR, \fB\-e\fR
Encrypt output file before writing.
.TP
\fB\--version\fR
Output version information and exit.
.SH AUTHOR
Written by Moshe Zadka, based on tapconvert's help messages
.SH "REPORTING BUGS"
To report a bug, visit \fIhttp://twistedmatrix.com/bugs/\fR
.SH COPYRIGHT
Copyright \(co 2000-2008 Twisted Matrix Laboratories.
.br
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
