.TH TWISTD "1" "Dec 2003" "" ""
.SH NAME
twistd \- run Twisted applications (TACs, TAPs)
.SH SYNOPSIS
.B twistd
[options]
.SH DESCRIPTION
Read an twisted.application.service.Application out of a file and runs it.
.TP
\fB\-n\fR, \fB\--nodaemon\fR 
Don't daemonize (stay in foreground)
.TP
\fB\-q\fR, \fB\--quiet\fR 
be a little more quiet
.TP
\fB\-p\fR, \fB\--profile\fR 
Run profiler
.TP
\fB\-b\fR, \fB\--debug\fR 
Run the application in the Python Debugger (implies nodaemon option).
Sending a SIGUSR2 signal to the process will drop it into the debugger.
.TP
\fB\-o\fR, \fB\--no_save\fR 
Do not save shutdown state
.TP
\fB\--originalname\fR
Behave as though the specified Application has no process name set, and run
with the standard process name (the python binary in most cases).
.TP
\fB\-l\fR, \fB\--logfile\fR \fI<logfile>\fR
Log to a specified file, - for stdout (default twistd.log).
The log file will be rotated on SIGUSR1.
.TP
\fB\--pidfile\fR \fI<pidfile>\fR
Save pid in specified file (default twistd.pid)
.TP
\fB\--chroot\fR \fI<directory>\fR
Chroot to a supplied directory before running (default -- don't chroot).
Chrooting is done before changing the current directory.
.TP
\fB\-d\fR, \fB\--rundir\fR \fI<directory>\fR
Change to a supplied directory before running (default .)
.TP
\fB\-r\fR, \fB\--reactor\fR \fI<reactor>\fR
Choose which ReactorCore event loop to use, such as 'poll' or 'gtk'.
.TP
\fB\--spew\fR
Write an extremely verbose log of everything that happens.  Useful for
debugging freezes or locks in complex code.
.TP
\fB\-f\fR, \fB\--file\fR \fI<tap file>\fR
Read the given .tap file (default twistd.tap)
.TP
\fB\-x\fR, \fB\--xml\fR \fI<tax file>\fR
Load an Application from the given .tax (XML) file.
.TP
\fB\-s\fR, \fB\--source\fR \fI<tas file>\fR
Load an Application from the given .tas (AOT Python source) file.
.TP
\fB\-y\fR, \fB\--python\fR \fI<python file>\fR
Use the variable "application" from the given Python
file. This setting, if given, overrides \fB\-f\fR.
.TP
\fB\-g\fR, \fB\--plugin\fR \fI<plugin name>\fR
Read config.tac from a plugin package, as with \fB\-y\fR.
.TP
\fB\--syslog\fR
Log to syslog, not to file.
.TP
\fB\--prefix\fR \fI<prefix>\fR
Use the specified prefix when logging to logfile. Default is "twisted".
.PP
Note that if \fBtwistd\fR is run as root, the working directory is \fInot\fR
searched for Python modules.
.SH AUTHOR
Written by Moshe Zadka, based on twistd's help messages
.SH "REPORTING BUGS"
Report bugs to <twisted-python@twistedmatrix.com>.
.SH COPYRIGHT
Copyright \(co 2003 Matthew W. Lefkowitz
.br
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
.SH "SEE ALSO"
mktap(1)
