## This file was generated by tap2ntsvc, with the command line:
##   C:/cygwin/home/PASS Program/tap2ntsvc.py -n example example.tac

import win32serviceutil, win32service

configfile = "example.tac"
cftype = "python"

class sayward_ServiceControl(win32serviceutil.ServiceFramework):

    _svc_name_ = "example"
    _svc_display_name_ = "example run by Twisted"

    def SvcDoRun(self):
        #### from twisted.internet import win32eventreactor
        #### win32eventreactor.install()

        f = file('c:/sayward.log', 'a')  # FIXME
        from twisted.python.log import startLogging
        startLogging(f)
        
        from twisted.application import service
        from twisted.internet import reactor
        
        svc = service.IService(service.loadApplication(configfile,
                                                       cftype))
        svc.startService()
        reactor.run()

        

    def SvcStop(self):
        self.ReportServiceStatus(win32service.SERVICE_STOP_PENDING)
        from twisted.internet import reactor
        reactor.stop()


if __name__ == '__main__':
    win32serviceutil.HandleCommandLine(sayward_ServiceControl)
