## This file was generated by tap2ntsvc, with the command line:
##   C:/cygwin/home/PASS Program/cvs/Twisted/sandbox/moonfallen/tap2ntsvc.py example.tac

import win32serviceutil, win32service

configfile = "example.tac"
cftype = "python"

class example_ServiceControl(win32serviceutil.ServiceFramework):

    _svc_name_ = "example"
    _svc_display_name_ = "example run by Twisted"

    def SvcDoRun(self):
        #### from twisted.internet import win32eventreactor
        #### win32eventreactor.install()

        f = file('c:/example.log', 'a')  # FIXME
        from twisted.python.log import startLogging
        startLogging(f)
        
        from twisted.application import service, app
        from twisted.internet import reactor
        
        a = service.loadApplication(configfile, cftype)
        app.startApplication(a, 1)
        reactor.run()

        

    def SvcStop(self):
        self.ReportServiceStatus(win32service.SERVICE_STOP_PENDING)
        from twisted.internet import reactor
        reactor.stop()


if __name__ == '__main__':
    win32serviceutil.HandleCommandLine(example_ServiceControl)
