#
# For documentation: https://docs.codecov.io/docs/codecovyml-reference
# Twisted settings: https://codecov.io/gh/twisted/twisted/settings/yaml
#
# We want 100% coverage for new patches to make sure we are always increasing
# the coverage.
#
codecov:
  token: fb52015a-b78e-4d89-a6e0-a4829aea2efa
  require_ci_to_pass: yes
  notify:
    # We have at least 5 builds in GitHub Actions,
    # so try not to send the reports too soon with partial results.
    after_n_builds: 5
    wait_for_ci: yes

coverage:
  precision: 2
  round: down
  status:
    patch:
      default:
        # New code should have 100% CI coverage as the minimum
        # quality assurance measurement.
        # If there is a good reason for new code not to have coverage,
        # add inline pragma comments.
        target: 100%
    project:
      default:
        # Temporary allow for a bit of slack in overall code coverage due to
        # swinging coverage that is not triggered by changes in a PR.
        # See: https://twistedmatrix.com/trac/ticket/10170
        threshold: 0.02%


# We don't want to receive general PR comments about coverage.
# We have the commit status checks and that should be enough.
# See https://docs.codecov.io/docs/pull-request-comments
comment: false

# See https://docs.codecov.io/docs/github-checks
github_checks:
  # We want codecov to send inline PR comments for missing coverage.
  annotations: true
