
# Copyright (c) Twisted Matrix Laboratories.
# See LICENSE for details.

#
# $Id: __init__.py,v 1.1 2002/03/18 23:33:48 jh Exp $

__doc__ = '''
Subpackage containing the modules that implement the command line tools.
Note that these are imported by script stubs generated by "setup.py".
'''

