.TH FAUCET "1" "July 2001" "" ""
.SH NAME
faucet \- use a twisted reality Pump server
.SH SYNOPSIS
.B faucet 
.I [--toolkit <toolkit>]
.SH DESCRIPTION
.TP
\fB\--toolkit\fR \fI<toolkit>\fR
Use given toolkit for user interface. Default is "tk".
The valid options are "tk" and "gtk".
.SH AUTHOR
Written by Moshe Zadka, based on twistd's help messages
.SH "REPORTING BUGS"
Report bugs to <twisted-python@twistedmatrix.com>.
.SH COPYRIGHT
Copyright \(co 2000 Glyph Lefkowitz
.br
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
