.TH GNUSTO "1" "July 2001" "" ""
.SH NAME
gnusto \- generate map pickles
.SH SYNOPSIS
.B gnusto 
.I mapName pickleName sourceName
.SH DESCRIPTION
Takes the twisted.reality generated python source in a map ("mapName")
and generates a pickle ("pickleName") as well as a source representation
of it ("sourceName", which should be identical to the code in "mapName"
unless manual changes were made to the source).
.SH AUTHOR
Written by Moshe Zadka, based on twistd's help messages
.SH "REPORTING BUGS"
Report bugs to <twisted-python@twistedmatrix.com>.
.SH COPYRIGHT
Copyright \(co 2000 Matthew W. Lefkowitz
.br
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
