.TH HLINT "1" "July 2001" "" ""
.SH NAME
hlint \- check an HTML file for non-compliance with the twisted.lore format
.SH SYNOPSIS
.B hlint [file [file ...]]
.SH DESCRIPTION
Read each specified file and report errors. 
.SH AUTHOR
Written by Moshe Zadka
.SH "REPORTING BUGS"
Report bugs to <twisted-python@twistedmatrix.com>.
.SH COPYRIGHT
Copyright \(co 2000 Matthew W. Lefkowitz
.br
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
.SH "SEE ALSO"
mktap(1)
