.TH TKMKTAP "1" "Nov 2002" "" ""
.SH NAME
tkmktap \- create twisted.servers
.SH SYNOPSIS
.B tkmktap
.SH DESCRIPTION
.TP
Run the Tk GUI version of mktap(1)
.SH AUTHOR
Written by Jp Calderone, based on the im.1 man page
.SH "REPORTING BUGS"
Report bugs to <twisted-python@twistedmatrix.com>.
.SH COPYRIGHT
Copyright \(co 2000 Matthew W. Lefkowitz
.br
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
