.TH TRIAL "1" "January 2003" "" ""
.SH NAME
trial \- run unit tests
.SH SYNOPSIS
.B trial [-m \fImodule\fR [-m \fImodule\fR ... ]] [-p \fIpackage\fR [-p \fIpackage\fR]]
.PP
.B trial --help
.SH DESCRIPTION
.PP
trial loads and executes a suite of unit tests, obtained from modules and 
packages listed on the command line.
The \fB\--help\fR prints out a usage message to standard output.
.TP
\fB-m\fR, \fB--module\fR <module>
Module containing test cases.
.TP
\fB-p\fR, \fB--package\fR <package>
Package containing modules that contain test cases.
trial loads modules named 'test_' within the given package.
.TP
\fB-l\fR, \fB--logfile\fR <logfile>
Log exceptions (and other things) to the given logfile.
.SH AUTHOR
Written by Jonathan M. Lange
.SH "REPORTING BUGS"
Report bugs to <twisted-python@twistedmatrix.com>.
.SH COPYRIGHT
Copyright \(co 2003 Matthew W. Lefkowitz
.br
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
