.TH TWISTD "1" "July 2001" "" ""
.SH NAME
twistd \- run twisted.internet.main.Application pickles
.SH SYNOPSIS
.B twistd
[options]
.SH DESCRIPTION
Read an twisted.internet.main.Application out of a file and runs it.
.TP
\fB\-n\fR, \fB\--nodaemon\fR 
Don't daemonize (stay in foreground)
.TP
\fB\-q\fR, \fB\--quiet\fR 
be a little more quiet
.TP
\fB\-p\fR, \fB\--profile\fR 
Run profiler
.TP
\fB\-b\fR, \fB\--debug\fR 
Run the application in the Python Debugger. (implies nodaemon)
.TP
\fB\-o\fR, \fB\--no_save\fR 
Do not save shutdown state
.TP
\fB\-l\fR, \fB\--logfile\fR \fI<logfile>\fR
Log to a specified file, - for stdout (default twistd.log).
The log file will be rotated on SIGUSR1.
.TP
\fB\--pidfile\fR \fI<pidfile>\fR
Save pid in specified file (default twistd.pid)
.TP
\fB\-d\fR, \fB\--rundir\fR \fI<directory>\fR
change to a supplied directory before running (default .)
.TP
\fB\-f\fR, \fB\--file\fR \fI<tap file>\fR
Read the given .tap file (default twistd.tap)
.TP
\fB\-y\fR, \fB\--python\fR \fI<python file>\fR
Use the variable "application" from the given Python
file. This setting, if given, overrides \fB\-f\fR.
.TP
\fB\-g\fR, \fB\--plugin\fR \fI<plugin name>\fR
Read config.tac from a plugin package, as with \fB\-y\fR.
.SH AUTHOR
Written by Moshe Zadka, based on twistd's help messages
.SH "REPORTING BUGS"
Report bugs to <twisted-python@twistedmatrix.com>.
.SH COPYRIGHT
Copyright \(co 2000 Matthew W. Lefkowitz
.br
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
.SH "SEE ALSO"
mktap(1)
