#!python
"""A useless program for testing processes on win32."""

import sys, os
import time
import msvcrt
# kludgy - this is probably a python bug ... stderr normally puts wrong line
# endings
msvcrt.setmode(sys.stderr.fileno(), os.O_BINARY)

def slowprint(st, writeable=sys.stdout):
    for c in st:
        writeable.write(c + os.linesep)
        time.sleep(0.1)

def run(argv=sys.argv):
    if len(argv) == 1 or argv[1] == 'stdout':
        slowprint('123')
        sys.exit(0)
    if argv[1] == 'stderr':
        slowprint('abc', sys.stderr)
        sys.exit(0)
    if argv[1] == 'stdin':
        l = sys.stdin.readline()
        slowprint(l[:-1]) # don't print extra newline
        sys.exit(0)
    if argv[1] == 'abort':
        sys.exit(1)

if __name__ == '__main__':
    run()
