#!/bin/sh
if test -x /usr/bin/update-menus; then update-menus; fi

NAME=python2.1-twisted
case "$1" in
        configure|abort-upgrade|abort-remove|abort-deconfigure)
		dpkg --listfiles $NAME | grep '\.py$' | \
		     xargs -n 1 /usr/bin/python2.1 -c 'import py_compile,sys;py_compile.compile(sys.argv[1])'
		dpkg --listfiles $NAME | grep '\.py$' | \
		     xargs -n 1 /usr/bin/python2.1 -O -c 'import py_compile,sys;py_compile.compile(sys.argv[1])'
        ;;
esac
