#!/bin/sh
name=`dpkg-parsechangelog |grep Source | awk -F: '{print $2}'|tr -d ' '`
version=`dpkg-parsechangelog |grep Version | awk -F: '{print $2}'|awk -F- '{print $1}'|tr -d ' '`
build=../debian-build
dir=$build/$name-$version
mkdir $dir
cp -ar * $dir
cd $build
find . -name CVS | xargs rm -rf
tar czf ${name}_$version.orig.tar.gz $name-$version
cd $dir
dpkg-buildpackage -rfakeroot -uc -us
cd ..
rm -rf $name-$version
