#!/bin/sh
rm -f doc/howto/book.*
rm -f doc/*/*.xhtml
find . -name "*.pyc" | xargs rm -f
if [ -x /usr/bin/fakeroot ]; then fakeroot debian/rules clean;fi > /dev/null
rm -rf _trial_temp
find . -name ".#*" | xargs rm -f
rm twisted/test/myrebuilder.py
