#!/bin/sh
rm -f doc/howto/book.*
rm -f doc/*/*.xhtml
find . -name "*.pyc" | xargs rm -f
if [ -x /usr/bin/fakeroot ]; then fakeroot debian/rules clean;fi > /dev/null
rm -rf _trial_temp
find . -name ".#*" | xargs rm -f
rm -f twisted/test/myrebuilder.py
for x in doc/api/*.html doc/api/*.css; do rm -f $x; done
rm -f doc/index.xhtml
