#!/usr/bin/env python
# system
import os, sys

# ***** RISE FROM YOUR GRAVE! *****
import twisted.web.microdom
sys.modules['xml'] = twisted
twisted.dom = twisted.web
sys.modules['xml.dom'] = twisted.web
twisted.web.minidom = twisted.web.microdom
sys.modules['xml.dom.minidom'] = twisted.web.microdom

#it'd be nice to get this working
#im = __import__
#def myimport(*args):
#    try: 
#        return im(*args)
#    except:
#        return FakeModule()

#__builtins__.__import__ = myimport

class FakeClass: pass
class FakeModule:
    def __getattr__(self, attr):
        return FakeClass

# initial twisted
from twisted.python import reflect
from twisted.internet import reactor
# epydoc
from epydoc.cli import cli

modnames = []
def addMod(arg, path, files):
    for fn in files:
        file = os.path.join(path, fn).replace('/__init__', '')
        if file[-3:] == '.py' and not file.count('/test/'):
            modName = file[2:-3].replace('/','.')
            try:
                #print 'pre-loading', modName
                reflect.namedModule(modName)
            except ImportError:
                print 'import error:', modName
            except:
                print 'other error:', modName
            else:
                modnames.append(modName)
osrv = sys.argv
sys.argv=["IGNORE"]
os.path.walk('./twisted', addMod, None)
sys.argv = osrv
sys.argv.extend(modnames)              # list of modules
cli()
