#!/bin/sh
set -e
baseurl=http://twistedmatrix.com/documents/TwistedDocs/TwistedDocs-$1/api/
templ=doc/howto/template.tpl
for doc in doc/howto doc/specifications; do
./bin/generatelore -a doc/api --docsdir $doc -t $templ --baseurl $baseurl 
done
