#!/usr/bin/python
import sys, re, os

tag = re.compile('</?\w+>')

def lower(m):
    return m.group().lower()

s = open(sys.argv[1]).read()
s=tag.sub(lower, s)

open(sys.argv[1]+'.new', 'w').write(s)

os.rename(sys.argv[1]+'.new', sys.argv[1])
