#!/usr/bin/python
# usage: 
# * unpack ~radix/Releases/Twisted-<version>.tar.gz in /sid/home/you
# * if it is not a final version:
#   * mv Twisted-<version>/ Twisted-<old version>+<version>/
# * ssh -p 9022 localhost
# * run ./Twisted-<whatever>/admin/make-deb -d
#   * when launched into an editor, change the version number at the top
#     to <whatever>-1
# * exit
# * rm ~moshez/public_html/snapshot/*twisted*
# * cp /sid/home/you/*twisted* ~moshez/public_html/snapshot/
# * cd ~moshez/public_html/snapshot
# * ./createpackages
# celebrate
import os, sys, getopt

run_dch, install = 0, None

for (opt, val) in getopt.getopt(sys.argv[1:], "di:")[0]:
	if opt == "-d":
		run_dch = 1
	if opt == "-i":
		install = val

here = os.path.dirname(os.path.abspath(sys.argv[0]))
parent = os.path.dirname(here)
root = os.path.basename(parent)
print root
version = root.split("-")[1]

os.chdir(os.path.dirname(parent))
os.system("mv Twisted-%(version)s twisted-%(version)s" % vars())
os.system("tar czf twisted_%(version)s.orig.tar.gz "
                  "twisted-%(version)s" % vars())
os.chdir("twisted-%(version)s" % vars())
if run_dch:
	os.system("dch")
os.system("debuild -us -uc")

if install:
	current = os.getcwd()
	os.chdir("..")
	for file in os.listdir('.'):
		if not os.path.isfile(file):
			continue
		base = file.split("_")[0]
		os.system("rm -f %(install)s/%(base)s*" % vars())
		os.system("cp %(file)s %(install)s" % vars())
	os.chdir(install)
	os.system("%(current)s/admin/createpackages "
	          "%(current)s/admin/override" % vars())
