#!/bin/sh
set -e
cp admin/book.tex doc/howto
cd doc/howto
for file in *.html
    do ../../admin/latex.py $file
done
latex book.tex
latex book.tex
dvips -o book.ps book.dvi
ps2pdf13 book.ps book.pdf
rm *.eps *.tex *.aux *.log book.dvi book.toc
