#!/usr/bin/python
import os, sys

if sys.argv[1:2]==["-d"]:
	run_dch = 1
else:
	run_dch = 0

here = os.path.dirname(os.path.abspath(sys.argv[0]))
parent = os.path.dirname(here)
root = os.path.basename(parent)
print root
version = root.split("-")[1]

os.chdir(os.path.dirname(parent))
os.system("mv Twisted-%(version)s twisted-%(version)s" % vars())
os.system("tar czf twisted_%(version)s.orig.tar.gz "
                  "twisted-%(version)s" % vars())
os.chdir("twisted-%(version)s" % vars())
if run_dch:
	os.system("dch")
os.system("debuild -us -uc")
