#!/bin/sh
set -e
cp admin/book.tex doc/howto
./bin/html2latex -s doc/howto/*.html doc/man/*.html doc/specifications/*.html
cd doc/howto
latex book.tex
latex book.tex
latex book.tex
dvips -o book.ps book.dvi
ps2pdf13 book.ps book.pdf
rm *.eps *.tex *.aux *.log book.dvi book.toc ../man/*.tex \
   ../specifications/*.tex
