#!/bin/sh
rm twistd.log
./bin/mktap web --user -p 3080; ./bin/twistd -f web.tap
sleep 1
lynx http://twistedmatrix.com:3080/jh.twistd/python/moin.cgi/
lynx http://twistedmatrix.com:3080/radix.twistd/
lynx http://twistedmatrix.com:3080/z3p.twistd/
kill `cat twistd.pid`
./bin/mktap web --personal;./bin/twistd -f web.tap
sleep 1
lynx http://twistedmatrix.com/users/$USER.twistd/
kill `cat twistd.pid`
./bin/twistd -s admin/test.tas
sleep 1
lynx http://localhost:3080/
kill `cat twistd.pid`
./bin/twistd -y admin/echo.py
sleep 1
echo hello | nc -q 1 localhost 18899
kill `cat twistd.pid`
less twistd.log
