#!/usr/bin/env python

# Copyright (c) 2001-2004 Twisted Matrix Laboratories.
# See LICENSE for details.


print
print 'runtests is DEPRECATED!  Use trial --verbose twisted.test instead!'
print

### Twisted Preamble
# This makes sure that users don't have to set up their environment
# specially in order to run these programs from bin/.
import sys, os, string
if string.find(os.path.abspath(sys.argv[0]), os.sep+'Twisted') != -1:
    sys.path.insert(0, os.path.normpath(os.path.join(os.path.abspath(sys.argv[0]), os.pardir, os.pardir)))
#sys.path.insert(0, os.curdir)
### end of preamble

from twisted.scripts import trial

# People shouldn't really be passing -p to runtests; it's explicitly for twisted.test
sys.argv.extend(['-p', 'twisted.test'])
sys.argv.extend(['-l', 'test.log'])

trial.run()

