#!/bin/sh
# A couple notes.
# First, get a checkout (or a release, if one exists) of zpkgtools and Zope3.
# Make a ~/.zpkg.resources file that contains 

# zpkgsetup /path/to/zpkgtools/zpkgsetup
# zope /path/to/Zope3/src/zope
# zope.interface /path/to/Zope3/src/zope/interface

# This will make it so zpkg doesn't have to download
# zpkgsetup every time you run it.

# Typical way to run this file:
#   runzpkg -v 2.0.0 twisted
#   runzpkg -v 2.0.0 twisted.conch
#   runzpkg -v 2.0.0 --collection twistedsumo
# (--collection = include dependencies)

zpkg --support twistedzpkg \
     --distribution twistedzpkg.zpkgsupport.Distribution \
     -m ~/.zpkg.resources \
     -m resources.zpkgmap \
     $*

