#!/usr/bin/python
import re, sys

include = re.compile('@include (.*)')

for line in sys.stdin.readlines():
    m = include.match(line)
    if m:
        sys.stdout.write(open(m.group(1)).read())
    else:
        sys.stdout.write(line)
