.TH "pyhtmlizer" "1" "" "Twisted Matrix Laboratories" ""
.SH "NAME"
.LP 
pyhtmlizer \- pretty\-print Python source as HTML

.SH "SYNTAX"
.LP 
pyhtmlizer [\fI\-s|\-\-stylesheet\fR <\fIurl\fR>] <\fIfilename\fR>
.SH "DESCRIPTION"
.LP 
This generates a HTML document with Python source marked up with span elements.  To colorize, provide a stylesheet.
.SH "OPTIONS"
.LP 
.TP 
\fB\-\-stylesheet, \-s\fR <\fIurl\fR>
Links to the stylesheet at <\fIurl\fR>.
.TP 
\fB\-\-help\fR
Output help information and exit.
.TP
\fB\-v\fR, \fB\--version\fR
Output version information and exit.
