#!/usr/bin/python
import sys, glob, os

version = '%s.%s' % sys.version_info[:2]
dir = 'debian/python%s-twisted' % version

for file in os.listdir(os.path.join(dir, 'usr/bin')):
    os.symlink(file, os.path.join(dir, 'usr/bin', file[:-len(version)]))

suffix = '.1.gz'

for file in os.listdir(os.path.join(dir, 'usr/share/man/man1')):
    target = file[:-len(version+suffix)]+suffix
    os.symlink(file, os.path.join(dir, 'usr/share/man/man1', target))
