name: Build wheels

on:
  push:
    branches: [ trunk ]
  pull_request:
    branches: [ trunk ]

jobs:
  build_wheel:
    runs-on: ${{ matrix.os }}
    env:
      TOXENV: "wheel"
    strategy:
      matrix:
          os: [ubuntu-20.04 , macos-10.15, windows-2019]
          python-version: [3.5, 3.6, 3.7, 3.8, 3.9.0-rc.2]

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    - name: Display Python information
      run: |
        python --version
        python -c "import sys; print(sys.prefix)"
        python -c "import sys; print(sys.exec_prefix)"
        python -c "import sys; print(sys.executable)"
        python -c "import struct; print(struct.calcsize('P') * 8)"
        python -c "print('\nENVIRONMENT VARIABLES\n=====================\n\n')"
        python -c "import os; [ print(e,v) for (e,v) in os.environ.items() ]" 

    - name: Get pip cache dir
      id: pip-cache
      run: |
        python -c "from pip._internal.locations import USER_CACHE_DIR; print('::set-output name=dir::' + USER_CACHE_DIR)"

    - uses: actions/cache@v2
      with:
        path: ${{ steps.pip-cache.outputs.dir }}
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
        restore-keys: |
            ${{ runner.os }}-pip-

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip tox
        tox --notest

    - name: Build wheels on ${{ runner.os }} / Python ${{ matrix.python-version }}
      run: |
        python --version
        tox -q

    - uses: actions/upload-artifact@v2
      with:
        name: twisted-artifact-${{ runner.os }}-${{ matrix.python-version }}
        path: ${{ github.workspace }}/dist/*.whl
        if-no-files-found: error
