parameters:
- name: imageName
  type: string
  default: 'macOS-latest'
# Must be a mapping of id-suitable-name -> actual version number with dot
- name: pythonVersions
  type: object


jobs:
- ${{ each pyver in parameters.pythonVersions }}:
  - job: ${{ format('macos_{0}', pyver.key) }}
    displayName: ${{ format('MacOS Py{0}', pyver.value) }}
    pool:
      vmImage: ${{ parameters.imageName }}
    steps:
    - template: 'run_test_steps.yml'
      parameters:
        platform: macos
        pythonVersion: ${{ pyver.value }}
